hardware/generate.py
hardware/tests/test_generate.py

Fix typo in generate_dict from generate.py
```try:
result[newkey] = merge(result[key], val)
except KeyError:
result[newkey] = val
```
For exemple with range `=node1-3` the value of key is `node1-3`.
So this key never exist in the `result` array. You always go to KeyError exception.
`result[key]` in `merge` will be replaced by `result[newkey]` (newkey example : node1).

Fix typo in generate_dict from generate.py (with tests)

---

hardware/detect.py
hardware/tests/test_detect.py

As per issue 206 in edeploy, we have systems where serial numbers are .... weird.
We have system that are even much more evil like DMI not providing any
unique ID at all...
This patch is trying to solve all that different cases.
If the serial is known to be buggy then we search for a possible
fallback in the following order :
- system uuid
- motherboard serial
- MAC address of the first nic
Note that the system uuid will be used unless it is known to be buggy or empty.
If a system doesn't provide any valid 'product SN' or 'product uuid' or
'motherboard serial' (yes this does exist), then we fallback on the last
unique ID we have on a system which is the mac address of one nic : this
is not optimal but at least that makes the installation process staying
alive. That's really a workaround.

detect: Adding more serial id fallbacks

---

hardware/state.py
hardware/tests/test_state.py

When a mac address is not provided by the cmdb
this commit make hardware_info to not add
a 'none' value.

hardware/state.py: remove none mac

---

hardware/benchmark/__init__.py
hardware/benchmark/cpu.py
hardware/benchmark/disk.py
hardware/benchmark/mem.py
hardware/benchmark/utils.py
hardware/detect.py
hardware/tests/test_benchmark_cpu.py
hardware/tests/test_benchmark_disk.py
hardware/tests/test_benchmark_mem.py
requirements.txt

This patch is adding support for benchmark tests as part of the
hardware-detect tool.
The test is optional and can be activated by passing the --benchmark
parameter to the tool. The parameter supports passing multiple values,
acceptable values right now are "disk", "cpu" and "mem".
Another parameter --benchmark-disk-destructive have been added and if
set it will turn on the destructive mode for the disk benchmark.
The new help menu:
usage: hardware-detect [-h] [-H] [--benchmark component [component ...]]
[--benchmark-disk-destructive]
optional arguments:
-h, --help            show this help message and exit
-H, --human           Print output in human readable format
--benchmark component [component ...], -b component [component ...]
Run benchmark for specific components. Valid
components …

Add support for benchmark tests

---

hardware/benchmark/mem.py
requirements.txt

psutil was used just to get the amount of available memory in the system,
psutil makes it nice to be able to do it in multiple platforms like bsd,
linux and windows. But since we only run this code on linux we can get
this information directly from /proc/meminfo so that we don't need to
add an extra dependency.

Remove the psutil dependency

---

hardware/cardiff/cardiff.py
hardware/cardiff/check.py
hardware/cardiff/compare_sets.py
hardware/megacli.py

This patch changes all 'print()' statements to 'print("")'.
Without the empty string, this was printing '()' instead of the
intended empty line.

Fix empty print statements

---

hardware/cardiff/cardiff.py

Since commit 84cb10a5c96a6ed03bd39141a455c733e0932cbc, the gnuplot call
was avoiding the "\n" to be expanded properly.
This patch does insure the \n to be expanded making the gnuplot header
readable again.

cardiff: Fixing gnuplot header

---

hardware/cardiff/cardiff.py
hardware/cardiff/check.py

When computing the metrics, it's important to keep them sorted in the
same order unless what will compare apples & pears.
We had a case where disks IOps where mixed with Bandwidth leading to
such gnuplot file :
1 12054.00 11.00
2 24509.00 22.00
3 23.00    26351.00
4 20.00    25320.00
5 19.00    26291.00
6 27754.00 22.00
7 26923.00 18.00
8 33677.00 25.00
For lines 3,4,5 IOps are mixed with the Bandwidth leading to stupid
graphs.
This patch does insure that modes are always sorted to prevent such
case. Note that storage modes are sorted reversly to keep the bandwidth
first.

cardiff: Reworking modes ordering

---

hardware/cardiff/cardiff.py
hardware/cardiff/check.py
hardware/cardiff/utils.py
hardware/tests/test_cardiff_check.py
tox.ini

This PR is linked to PR #31.
The testing code was not using functions from check and so duplicated most of the filtering code.
This PR is split in two commits ::
- One to make the check.*() functions having a clean behavior for being called by the testing code
- one to change the code in the test code to reuse the check.*() code
Once this PR will be merged, PR#31 can be merged too.
Thanks,

Cardiff grouping fix

---

hardware/cardiff/cardiff.py
hardware/cardiff/check.py

Just discovered that no code was calling the hardware physical disks
comparaison while it's one of the key component on a server.
This patch is simply making the proper call to get hpa & megacli PD
reporting.
It also add a couple of unique IDs that are reported by the controller
but that should not be taken in consideration when comparing the
physical disks (PDs).

cardiff: Comparing hardware physical disks

---

hardware/matcher.py
hardware/tests/test_matcher.py

This patch add a new spec helper called 'range'
It does allow putting a matching rule to check if a value is part of a range.
The prototype is like range(lower_bound, upper_bound) and the code return True
if (lower_bound <= x <= upper_bound).
A typical usage would be :
('ipmi', '+12 V', 'value', 'range(11.8, 12.2)'),

matcher: Adding range() function

---

hardware/areca.py
hardware/cardiff/compare_sets.py
hardware/detect.py
hardware/detect_utils.py
hardware/diskinfo.py
hardware/generate.py
hardware/megacli.py
hardware/tests/test_diskinfo.py
requirements.txt

* Replace long(500) with 500. long type was replaced with the int
type in Python 3.
* Fix a commented print statement
* Replace xrange() with range() or six.moves.range() depending on the
size of the range.
* Use universal_newlines to get stdout as text (Unicode) on Python 3
instead of bytes. Use also communicate() which is more reliable and
standard than stdout.read().
* Replace long(str) with int(str)

Fix Python 3 issues

---

README.rst

New comers doesn't get what are the runtime deps. Let's make that more
explicit unless they could misdetect their platform.

documentation: Making runtime deps explicit

---

hardware/detect.py
hardware/infiniband.py
hardware/tests/test_detect.py
test-requirements.txt
tox.ini

Currently hardware runs dmidecode to grab the system-uuid but on systems
that don't have DMI none is returned.  We can generate one from the
vendor and serial if that's found.  Or with a modern[1] OPAL firmware we
can just return the one from the device-tree
[1] Ok unreleased but with an open [RFE](https://github.com/open-power/skiboot/issues/193) ;P

Add a system UUID on ppc64le

---

CONTRIBUTING.rst
README.rst

Hi!
Adding how to install `hardware`
Replace oldest repository from enovance to redhat-cip

Adding how to install

---

hardware/detect.py
hardware/rtc.py

This will allow to add a new validation before deploying so that
tripleo won't deploy anything until hardware clocks are set to RTC.
This setting is mandatory in order to prevent any issues regarding
timezone, future-dated files and so on.
More information: https://storyboard.openstack.org/#!/story/2002926
Story: 2002926

New task in hardware detection: detect RTC setting.

---

hardware/hpacucli.py

ssacli is the new name for hp's tool. Let's try it first.

hardware/hpacucli.py: Adding ssacli support

---

hardware/hpacucli.py

While parsing the physical drives, the output of some versions of ssacli can report strings in various cases (upper/lower).
This patch makes the output in lower case to improve the matching.

hardware/hpacucli.py: Avoid PDs not being detected

---

.travis.yml
setup.cfg
tox.ini

Python 3.4 final release will be 3.4.10 in March 2019.
We should drop support for it in favor of python 3.6.

Drop support for python 3.4 in favor of 3.6

---

.gitignore
requirements.txt

The version of pbr currently supported is a bit old.
Increasing version supported to 1.0 or higher.
Also adding .eggs to gitignore.

Increasing pbr version

---

hardware/detect_utils.py

The 'raise' keyword should always call an exception.

Fixing empty raise statement

---

.testr.conf
test-requirements.txt
tox.ini

Rewriting tox commands and options to improve testing and
remove the need of testrepository and testscenarios.
Bumping min tox version to 2.0 changes the default behavior
in case of errors from commands from 'ignore' to 'abort'
and allows the use of passenv option.
Also setting python3 as default python base.

Rewriting tox.ini

---

hardware/detect.py
hardware/tests/samples/lscpu
hardware/tests/samples/lscpu-vm
hardware/tests/samples/lscpu-vmx
hardware/tests/samples/lscpux
hardware/tests/test_detect.py

This patch is about using lscpu to report cpu capabilities.
This is much more precise than lshw and offer new features like :
- detecting all caches level
- reporting numa structures
This patch also reports the scaling governor per logical processor if any defined.

Reworking CPU reporting

---

hardware/megacli.py

Commit 54a78530fca3bfe81cfa54fc96e19ee7688280ca introduced a typo which broken the code as in :
Traceback (most recent call last):
File "/usr/bin/hardware-detect", line 10, in <module>
sys.exit(main())
File "/usr/lib/python2.7/site-packages/hardware/detect.py", line 996, in main
_main(options)
File "/usr/lib/python2.7/site-packages/hardware/detect.py", line 921, in _main
detect_megacli(hrdw)
File "/usr/lib/python2.7/site-packages/hardware/detect.py", line 170, in detect_megacli
ctrl_num = megacli.adp_count()
File "/usr/lib/python2.7/site-packages/hardware/megacli.py", line 148, in adp_count
arr = run_and_parse('adpCount')
File "/usr/lib/python2.7/site-packages/hardware/megacli.py", line 142, in run_and_parse
res = run_megacli(*args)
File …

hardware/megacli.py: Fixing typo

---

hardware/detect.py

On a RHEL8 VM L3 Cache does not exist and so we fail with:
Traceback (most recent call last):
File "/bin/hardware-detect", line 10, in <module>
sys.exit(main())
File "/usr/lib/python3.6/site-packages/hardware/detect.py", line 996, in main
_main(options)
File "/usr/lib/python3.6/site-packages/hardware/detect.py", line 923, in _main
if not detect_system(hrdw):
File "/usr/lib/python3.6/site-packages/hardware/detect.py", line 666, in detect_system
get_cpus(hw_lst)
File "/usr/lib/python3.6/site-packages/hardware/detect.py", line 740, in get_cpus
processor), item.lower(), lscpu[item]))
KeyError: 'L3 cache'
Only add the caches if they exist in the lscpu dict
Co-Authored-By: Damien Ciabrini <dciabrin@redhat.com>
Signed-off-by: Michele Baldessari <michele@acksyn.org>

Make the cache info collection more robust

---

hardware/detect.py
hardware/tests/samples/lscpu_aarch64
hardware/tests/samples/lscpu_ppc64le
hardware/tests/samples/lscpux_aarch64
hardware/tests/samples/lscpux_ppc64le
hardware/tests/test_detect.py

Certain lscpu keys don't make sense on ppc64le (e.g Vendor, CPU Family,
Stepping) and others are strings rather than ints (e.g. Model).
Handle these difference.
While we're looking at this NUMA nodes are represented differently on
ppc64le systems in that they are sparse and may have no CPUs allocated.

Handle Architecture CPU information.

---

hardware/benchmark/cpu.py
hardware/tests/test_benchmark_cpu.py

The output of the commands is considered bytes by Python 3.x and
causes a TypeError exception when looking for a string in it.
Converting to text will fix that.
Fix #87

Fix error cpu benchmark with Python 3.x

---

hardware/detect.py
hardware/tests/samples/lscpu
hardware/tests/test_detect.py

If the value of an entry detected by lscpu contains a colon ':'
the execution fails with ValueError: too many values to unpack
exception.
This patch prevents that situation, splitting each line after the
first occurrence of the colon ':' symbol only.

Split lscpu output on first colon occurrence only

---

hardware/detect.py
hardware/tests/test_detect.py

We call dmesg directly inside its parsing function instead of
passing the huge output as parameter to the function.
This helps also in keeping consinstency in case of refactoring.

Call dmesg inside its parsing function

---

hardware/generate.py
hardware/smart_utils.py

First of a series of cosmetic changes to migrate to new pep8 style.
The main change is cutting the lines to less than 80 characters.
More style changes may be applied depending on the module.
This patch does not include any functional change.

Cosmetic change to adapt to new pep8 style

---

hardware/benchmark/disk.py
hardware/tests/test_benchmark_disk.py

when running the benchmark script with python 3, the command
output is bytecode and not str.
This patch fixes the parsing converting the output in the
appropriate format according to Python version used.

[Bugzilla 1729237] Fix benchmark output for disks

---

hardware/detect.py
hardware/rtc.py

hardware-detect can fail under these two cases:
1) if 'lscpu' doesn't return a 'NUMA node(s)' key,
2) if 'timedatectl' isn't available.
These have been observed using 'hardware' in tinyipa, part of the openstack ironic-python-agent-builder repository.
This patch catches these errors and allows detect-hardware to exit successfully despite these error conditions.

Improve resiliency to failure

---

hardware/benchmark/disk.py
hardware/cardiff/check.py

Adapting perf messages to use string format instead of
concatenation.
Also, using a variable to define the output message and splitting
command line in disk.py.
Follow up to #103

Use string format instead of concatenation

---

hardware/benchmark/mem.py
hardware/tests/test_benchmark_mem.py

The output of the commands is considered bytes by Python 3.x and
causes a TypeError exception when looking for a string in it.
Converting to text will fix that.
Fixes #107

Fix error mem benchmark with Python 3

---

hardware/tests/results/detect_results.py
hardware/tests/samples/lscpu
hardware/tests/samples/lscpux

There was no reason to change that, and it's contradictive from
the trademark point of view.

Rename FakeAMD back to AuthenticAMD

---

.travis.yml
doc/requirements.txt
doc/source/conf.py
requirements-doc.txt
requirements.txt
test-requirements.txt
tox.ini

Reviewed doc requirements and configuration.
Removed unmaintained oslosphinx in preparation of moving to
openstackdocstheme.
Removed general Babel req and added to testing.
Fixed sphinx, Babel and mock version requirements to align with
latest Python 3.x versions.

Enabling docs testing in travis

---

.travis.yml
hardware/generate.py
hardware/matcher.py
setup.cfg
tox.ini

This patch drops support and testing for Python 3.5 in favor of
Python 3.8
Also adding docs env to tox.ini as follow-up to #110

Drop Python 3.5 in favor of Python 3.8

---

.travis.yml

Start using tox-travis plugin to run tests on travis.
This allows more flexibility and integration with travis.
Also starts running all tests with all Python versions supported.

Use tox-travis for testing

---

.travis.yml

Looks like travis has a good support for bionic now, let's drop
xenial and use bionic instead.
This patch depends on #112

Use bionic

---

.travis.yml
doc/requirements.txt
setup.cfg
tox.ini

With this patch we stop explicit support for Python 2.x.
From now on, all tests are executed with Python 3.x only; future
versions of the code won't guarantee working with versions prior
to 3.6 of Python.

Stop supporting Python 2.x

---

tox.ini

Enforce the correct version based on tox environment adding the
option ignore_basepython_conflict available since tox 3.1.0 [0].
[0] https://tox.readthedocs.io/en/latest/config.html#conf-ignore_basepython_conflict

Use correct python version for tox based on env

---

hardware/cardiff/check.py

Groupings based on network disk performance should not
be generated for nodes without network drives.
This fixes #120.

Skip network drive grouping when network drives not detected

---

hardware/detect.py
requirements.txt

Now that we don't support Python 2, we can use the built-in ipaddress
module. Also remove the dependency on its Python 2 backport.

Drop the dependency on netaddr

---

hardware/benchmark/cpu.py
hardware/benchmark/disk.py
hardware/benchmark/mem.py
hardware/generate.py
hardware/smart_utils.py
hardware/tests/test_benchmark_cpu.py
hardware/tests/test_benchmark_disk.py
hardware/tests/test_benchmark_mem.py
hardware/tests/test_detect.py
hardware/tests/test_smart_utils.py
requirements.txt

Since we've dropped support for Python 2.7 and we're going for
Python 3.x only, we don't need the six library anymore.

Stop using six library

---

hardware/detect.py
hardware/tests/results/detect_results.py
hardware/tests/samples/lscpu-7302
hardware/tests/samples/lscpu-7302x
hardware/tests/test_detect.py

The actual code was confused by a syntax like :  0,1,16,17
It was considering each value as a number of cores reporting 34 to this example.
This patch modify the logic and count only one core per comma when there isn't any dash ("-") in it.
This add a sample of an AMD 7302 so have this configuration.

detect: Fixing numa cpu_count computation

---

hardware/detect.py
hardware/tests/test_detect.py

The "mapping" and "default" parameters of this functions
are used in only one invocation. Remove them to simplify the
code.
This function now raises IOError instead of returning an 'exists' flag.

simplify _from_file function

---

hardware/rtc.py

The CalledProcessError exception needs to be handled, similar to
https://github.com/redhat-cip/hardware/blob/master/hardware/detect_utils.py#L29.

Handle check_output exception for rtc

---

hardware/detect.py
hardware/tests/test_detect.py

Prior to kernel version 4.3,
/sys/devices/system/cpu/cpu{}/cpufreq/scaling_governor was used
instead of /sys/devices/system/cpu/cpufreq/policy{}/scaling_governor.
Try to access the first file in case the second one does not exist.

Get the CPU scaling governor on kernels < 4.3

---

hardware/areca.py
hardware/benchmark/disk.py
hardware/detect.py
hardware/generate.py
hardware/hpacucli.py
hardware/matcher.py
hardware/megacli.py
hardware/state.py
hardware/tests/test_hpacucli.py
test-requirements.txt
tox.ini

The new version enables a lot of standard flake8 checks, so a few
fixes are required. W503 is disabled as it conflicts with W504
and the latter seems to be preferred nowadays.

Bump hacking to 3.0.0

---

test-requirements.txt

Full py3 compatible version.
Add all Python3 modules to stdlib list.

Set flake8-import-order min version to 0.17.1

---

hardware/areca.py
hardware/detect.py
hardware/tests/test_areca.py

Start moving stuff out of detect.
That will also allow us to stop passing the same huge list of data
between functions and modules.
In the long term it will help testing and converting to a more sane
schema.

Move detect_areca in the areca module

---

hardware/areca.py
hardware/detect.py
setup.py

On systems where both python2 & 3 are installed, its better enforcing python3.
If python points to python2, hardware-detect fails with the following message :
-bash-4.2# hardware-detect
Traceback (most recent call last):
File "/usr/bin/hardware-detect", line 6, in <module>
from hardware.detect import main
File "/usr/lib/python2.7/site-packages/hardware/detect.py", line 34, in <module>
from hardware import areca
File "/usr/lib/python2.7/site-packages/hardware/areca.py", line 99
def _run_and_parse(*args, rev=False):
Let's default to python3.

setup: Defaulting to python3

---

hardware/hpacucli.py

If no information are available from hpacucli for some reason,
the detect function should return an empty list and not a boolean
to prevent issues when parsing the main list.
See issue [1] for more info.
[1] https://bugs.launchpad.net/tripleo/+bug/1900158

Fix output of hpacucli when no info available

---

hardware/detect.py
hardware/detect_utils.py
hardware/tests/test_detect.py
hardware/tests/test_detect_utils.py

Being a generic helper function, get_uuid should be moved to
detect_utils.
This is also needed for the future refactor of detect_system.

Move logic to retrieve system uuid to detect_utils

---

test-requirements.txt

Versions of hacking from 3.1.0 until 4.0.0 NOT included are supposed
to require a safe version of flake8, so besides normale issues related
to minor version upgrades, we can safely use those versions.
Also forcing pycodestyle versions to be compatible with flake8 installed
by hacking.

Set safe version of hacking

---

hardware/detect.py
hardware/detect_utils.py
hardware/tests/test_detect.py
hardware/tests/test_detect_utils.py

Move functions that can be used by more classes and functions
to the detect-utils module as utils functions.

Move more generic functions to detect-utils

---

hardware/detect.py

Since the new detect functions in the separate modules return
lists, we should not append them to the final list but instead
extend it.
This fixes the issue described in [1] where the extra_hardware
plugin in ironic-inspector tries to convert the data collected
by the ipa ramdisk but gets an unexpected list inside a list.
[1] https://bugs.launchpad.net/tripleo/+bug/1901917

Fix final output

---

test-requirements.txt
tox.ini

Move test requirements for pep8 and coverage to tox.ini
Increase minversion of tox to support inline comments [1]
Also remove unneeded test requirements.
[1] https://tox.readthedocs.io/en/latest/changelog.html#v3-9-0-2019-04-17

Update requirements and tox minversion

---

hardware/detect.py
hardware/detect_utils.py

The code to get ddr timings info is based on a tool that is not
maintained since years and currently does not work.

Remove ddr timings info

---

setup.cfg

This adds "Requires-Python: >=3.6" to the PKG-INFO file, which will then
in turn be processed by PyPI and pip and prevent users on Python 2 from
being able to `pip install hardware`.

Add line to setup.cfg limiting to Python >=3.6

---

hardware/detect_utils.py
hardware/tests/test_detect_utils.py

Stop passing entire result list to parse_dmesg
Also refactor parse_ahci as a consequence

Refactor parse dmesg function

---

hardware/detect.py

The current unit tests are missing a check for the detect script.
Fixing breakage introduced by [1]
[1]https://github.com/redhat-cip/hardware/pull/181/commits/6da6ebb79955cc4717b1291199faeefd54265949

Fix regression in detect script

---

.github/workflows/docs-testing.yml
.github/workflows/pep8-testing.yml
.github/workflows/unit-testing.yml
setup.cfg

Python 3.6 support was deprecated and it's now removed.
The security support ended over 3 months ago.

Remove support for Python 3.6

---

test-requirements.txt
tox.ini

There is a compatibility issue between importlib-metadata 5.0.0 and
flake8 under Python 3.7 [1].
[1] https://github.com/python/importlib_metadata/issues/406

Pin importlib-metadata under 5.0.0 for Python 3.7

---

hardware/benchmark/disk.py
hardware/tests/test_benchmark_disk.py

The fio output parsed by the disk benchmark has changed around 2017 [1].
Parse JSON output instead. Closes #187.
[1] https://github.com/axboe/fio/commit/d694a6a7c02f577b2bb5d0ad24331b775acf6869

Fix parsing of fio output

---

hardware/benchmark/disk.py

If disks are large enough then FIO will write to stdout a warning that the default random generator is not sufficient. As this is written to stdout the subsequent attempt to parse the JSON will fail as it contains the warning before the JSON object.
To fix we can set the random generator to `tausworthe64` which will suppress the warning allow for the JSON to be parsed without error.
This issue has been noticed on disks around 64TB in size however could occur on smaller disks.
Fixes #201

fix: use `--random_generator=tausworthe64`
