hardware/matcher.py

remove debug print, it ends up in the result on stdout

remove debug print, it ends up in the result on stdout

---

hardware/detect.py
hardware/tests/test_detect.py

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1257517

Resist to an invalid UTF-8 string from the hardware detection

---

.travis.yml

Fixes according to http://docs.travis-ci.com/user/migrating-from-legacy/

.travis.yml: use the new infrastructure based on containers

---

hardware/detect.py

When reading the Logical Drive properties, the previous code was pretty
long and assumed the name of the properties to manipulate.
That was a pain as some properties were present sometimes but not on
some other.
This patch just make the code easier to read, more robust and reports
much more info as we had previously.
The principle is very easy to understand .... "just report what we have"....
That should have been like that since a while.

detect: Automatic megacli's LD description

---

hardware/megacli.py

Depending on the version or the distribution method, megacli could have
various casting like megacli or MegaCli.
This patch does add a method to find which one to use.
As we still run on python2.7, this patch reuse which() from python3 and
an homemade search_exec() function to find all possible name of the same
exec.
Therefore it's now possible to detect both of them and use it. We had a
case where megacli commands were not executed because of the name
cast...
Patch tested on an hypervisor running MegaCli.

megacli: Searching various version of megacli executable

---

hardware/areca.py
hardware/detect.py
hardware/tests/samples/areca_adsysinfo
hardware/tests/samples/areca_disks_info
hardware/tests/samples/areca_hddpwr_info
hardware/tests/samples/areca_hw_info
hardware/tests/samples/areca_sys_showcfg
hardware/tests/samples/areca_sysinfo
hardware/tests/test_areca.py

This patch is using the Areca cli tool to report info about the current
controller
A typical ouput looks like https://nopaste.me/view/dc0954da

detect: Adding Areca support

---

README.rst
doc/source/usage.rst
setup.cfg

* Move homepage to https://github.com/redhat-cip/hardware
* README: use a small badge for Travis CI.

Enhance documentation

---

.travis.yml
setup.cfg
tox.ini

Hi!
Adding support for python 3.5 including:
- tox
- travis
- pypi classifiers

support python 3.5

---

hardware/detect.py

Related to:
https://bugzilla.redhat.com/show_bug.cgi?id=1670606
Signed-off-by: Lon Hohberger <lon@metamorphism.com>
Signed-off-by: Lon Hohberger <lhh@redhat.com>

Use sysfs instead of forking sdparm for WCE/RCD

---

hardware/detect_utils.py

Partial fix for python 3.x, retro compatible with python 2.x
Fixes #48

Fixing parsing issues with python3.x in detect_utils

---

.travis.yml
setup.cfg
tox.ini

We should start testing and building with python 3.7

Adding support for python 3.7

---

hardware/tests/test_detect.py

Fixing two functions not being restored correctly.

Initial fixing of test_detect

---

hardware/detect.py

Using native argparse options to parse arguments passed to the
script.

Use pure argparse

---

hardware/detect.py
hardware/diskinfo.py
hardware/tests/test_diskinfo.py

Adding support for detecting nvme devices based on device names.
With this patch we can read basic information on nvme devices
including and not limited to name, size, vendor and model.
This has been successfully tested on a system with a single nvme
device.
This change does not include support for smart utils.
```
sudo ./hardware-detect -H
[...]
[('disk', 'logical', 'count', '1'),
('disk', 'nvme0n1', 'size', '512'),
('disk', 'nvme0n1', 'vendor', '0x144d'),
('disk', 'nvme0n1', 'model', 'SAMSUNG MZVLB512HAJQ-000L7'),
('disk', 'nvme0n1', 'revision', '0x00'),
('disk', 'nvme0n1', 'optimal_io_size', '0'),
('disk', 'nvme0n1', 'physical_block_size', '512'),
('disk', 'nvme0n1', 'rotational', '0'),
('disk', 'nvme0n1', 'nr_requests', '1023'),
('disk', 'nvme0n1', 'scheduler', 'none'),
('disk', …
```

Basic support for nvme devices

---

hardware/detect.py
hardware/smart_utils.py
hardware/smart_utils_info.py
hardware/tests/results/smart_utils_results.py
hardware/tests/samples/smartctl_nvme
hardware/tests/test_smart_utils.py

This patch allows parsing and reporting information from
SMART tools for nvme devices.

smart support for nvme devices

---

hardware/hpacucli.py

This fixes TypeError when running with python3

Fix hpacucli with python3

---

hardware/detect.py

This PR aims to improve the documentation / comments in hardware/detect.py.
It fixes some typo, modifies the formatting of some docstrings and create a new docstring for fix_bad_serial().

Fix typos, improve docstrings

---

.travis.yml
hardware/tests/results/detect_results.py
hardware/tests/test_detect.py
test-requirements.txt
tox.ini

Change TOX_ENV to correct TOXENV.
Run all tests for each python version.
Fixing pep8 errors.
Installing non bugged version of pyflakes.
Also excluding two flake8 tests for now, will fix in a follow-up.

Fix travis CI

---

hardware/detect.py
hardware/detect_utils.py
hardware/tests/test_detect.py
hardware/tests/test_detect_utils.py

We should import modules, not functions.
Also moving the function size_in_gb to detect_utils as it is in
fact a util function.

Import detect_utils as module

---

hardware/detect.py
hardware/megacli.py

Remove detect_megacli from detect and move it in the megacli module.
Also some refactoring of the same module to improve readability
and comply to pep8 standards.

Move detect_megacli in the megacli module

---

hardware/detect.py
hardware/diskinfo.py

Also some refactoring in diskinfo.

Move detect_disks to diskinfo module

---

hardware/detect.py
hardware/detect_utils.py
hardware/tests/test_detect.py
hardware/tests/test_detect_utils.py

Also fix docstrings in a couple of functions in detect_utils

Move 2 more functions to detect_utils

---

.travis.yml
setup.cfg

Also set Python 3 support only

Use ubuntu focal travis environment for tests

---

hardware/detect.py
hardware/detect_utils.py
hardware/ipmi.py

Some cleaning and refactoring as well.

Move ipmi detect logic to its module

---

hardware/detect.py
hardware/infiniband.py
hardware/ipmi.py

Move detect infiniband device info logic from detect to its own module.
Also fix docstring in ipmi module.

Refactor infiniband module

---

.github/workflows/docs-testing.yml
.github/workflows/pep8-testing.yml
.github/workflows/unit-testing.yml

Fix github actions not running on PRs

Run github actions on pull requests

---

hardware/smart_utils.py
hardware/smart_utils_info.py

Save some space and remove some duplicated code.

Move smart fields to smart_utils_info as dict

---

hardware/detect.py
hardware/detect_utils.py
hardware/tests/test_detect_utils.py

Stop passing the entire result list to detect_auxv

Refactor auxv detect function

---

hardware/matcher.py

[Trivial] Simplify chain relations

---

hardware/bios_hp.py
hardware/detect.py
hardware/tests/test_bios_hp.py

Refactor bios_hp module

---

hardware/areca.py

Skip areca check if cli64 is not installed

---

.github/workflows/docs-testing.yml
.github/workflows/pep8-testing.yml
.github/workflows/unit-testing.yml
setup.cfg
test-requirements.txt
tox.ini

Adjust requirements and setup config accordingly

Support Python 3.12 and remove Python 3.7

---

.github/workflows/docs-testing.yml
.github/workflows/pep8-testing.yml
.github/workflows/unit-testing.yml
setup.cfg
tox.ini

Minimum supported Python version is now 3.9

Remove Python 3.8 support
